version: '3.7'
services:
  dbpostgresql:
    container_name: db-java-monolith
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=java_monolith
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
